"""en_recall_cardsテーブルの作成

Revision ID: 0a2b23c2418c
Revises: 8b6144523b23
Create Date: 2025-06-14 13:15:43.517174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2b23c2418c'
down_revision: Union[str, None] = '8b6144523b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('en_recall_cards',
    sa.Column('recall_card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False, comment='質問'),
    sa.Column('answer', sa.String(), nullable=False, comment='答案'),
    sa.Column('correct_point', sa.Integer(), nullable=False, comment='正解ポイント'),
    sa.Column('review_deadline', sa.DateTime(timezone=True), nullable=False, comment='復習期限'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('recall_card_id')
    )
    op.create_index(op.f('ix_en_recall_cards_user_id'), 'en_recall_cards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_en_recall_cards_user_id'), table_name='en_recall_cards')
    op.drop_table('en_recall_cards')
    # ### end Alembic commands ###
