"""認証試行回数とロック状態フィールドの追加

Revision ID: 777d9bdd8427
Revises: a1128b857873
Create Date: 2025-06-07 09:14:58.681865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777d9bdd8427'
down_revision: Union[str, None] = 'a1128b857873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_codes', sa.Column('verification_attempts', sa.Integer(), nullable=True))
    op.add_column('verification_codes', sa.Column('is_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_codes', 'is_locked')
    op.drop_column('verification_codes', 'verification_attempts')
    # ### end Alembic commands ###
