"""学習履歴テーブルの追加

Revision ID: 83906269e4f1
Revises: f2c8097f3480
Create Date: 2025-05-25 07:21:00.488222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83906269e4f1'
down_revision: Union[str, None] = 'f2c8097f3480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('en_learning_histories',
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('learning_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('date', 'user_id')
    )
    op.create_index(op.f('ix_en_learning_histories_user_id'), 'en_learning_histories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_en_learning_histories_user_id'), table_name='en_learning_histories')
    op.drop_table('en_learning_histories')
    # ### end Alembic commands ###
