"""Alter MessageTestScoreModel

Revision ID: f2c8097f3480
Revises: 45b6378ade7e
Create Date: 2025-05-17 09:58:04.113384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c8097f3480'
down_revision: Union[str, None] = '45b6378ade7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('en_message_test_scores', 'user_answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('en_message_test_scores', 'user_answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
